CREATE TABLE gamedata.GameSave
(
    SaveId INT NOT NULL CONSTRAINT PK_GameSave_SaveId PRIMARY KEY IDENTITY(1,1),
    PlayerId UNIQUEIDENTIFIER NOT NULL, 
    WriteTime DATETIME2(0) NOT NULL DEFAULT GETUTCDATE(),
    RawSaveData VARCHAR(MAX) NOT NULL,
    SaveHash AS (CONVERT(CHAR(64), HASHBYTES('SHA2_256', LEFT(RawSaveData, 8000)))) PERSISTED,

    CONSTRAINT FK_PlayerId FOREIGN KEY (PlayerId) REFERENCES gamedata.Player(PlayerId)
);
GO

CREATE UNIQUE INDEX NCIX_SaveHash ON gamedata.GameSave(SaveHash);
GO
