CREATE TABLE gamedata.Player
(
    PlayerId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Player PRIMARY KEY DEFAULT NEWID(),
    ViewToken UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    PlayerName NVARCHAR(255) NULL,

    CONSTRAINT UQ_ViewToken UNIQUE (ViewToken),
    CONSTRAINT UQ_PlayerName UNIQUE (PlayerName)
);
