CREATE TABLE gamedata.Player
(
    PlayerID INT PRIMARY KEY IDENTITY(1,1),
    EditToken UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    ViewToken UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    PlayerName NVARCHAR(255) NULL,

    CONSTRAINT UQ_EditToken UNIQUE (EditToken),
    CONSTRAINT UQ_ViewToken UNIQUE (ViewToken)
);
